/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from shared/
 * Run 'npm run sync:shared' to update
 */

const ROLE = {
    FREE: "FREE",
    PREMIUM: "PREMIUM",
    PRO: "PRO",
    ADMIN: "ADMIN",
} as const;

export { ROLE };