// import type { Metadata } from 'next';
import { SearchQueryProvider } from './context/SearchQueryContext';

// export const metadata: Metadata = {
// 	title: 'Crockpot',
// 	description: 'Generated by create next app',
// };

export default function BrowsePageLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <SearchQueryProvider>{children}</SearchQueryProvider>;
}
