/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from shared/
 * Run 'npm run sync:shared' to update
 */

export const ROLE = {
  FREE: "FREE",
  PREMIUM: "PREMIUM",
  PRO: "PRO",
  ADMIN: "ADMIN",
} as const;

export const HOUSE_CATEGORY_ID = "6310a881b61a0ace3a1281ec";
export const WATER_ITEM_ID = "6310ad7242687f4a1cf7f26a";
