#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const HEADER = `/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from shared/
 * Run 'npm run sync:shared' to update
 */

`;

function cleanDirectory(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function copyDir(src, dest, addHeader = true) {
  // Ensure destination exists
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath, addHeader);
    } else if (entry.name.endsWith(".ts")) {
      let content = fs.readFileSync(srcPath, "utf8");

      if (addHeader) {
        content = HEADER + content;
      }

      fs.writeFileSync(destPath, content, "utf8");
      console.log(`  ✓ ${path.relative(dest, destPath)}`);
    }
  }
}

function syncShared() {
  const sharedSrc = path.join(__dirname, "..", "shared");
  const frontendDest = path.join(
    __dirname,
    "..",
    "apps",
    "frontend",
    "src",
    "shared"
  );
  const apiDest = path.join(__dirname, "..", "apps", "api", "src", "shared");

  console.log("🔄 Syncing shared files...\n");

  // Clean old generated files
  console.log("🧹 Cleaning old generated files...");
  cleanDirectory(frontendDest);
  cleanDirectory(apiDest);

  console.log("\n📦 Frontend (apps/frontend/src/shared):");
  copyDir(sharedSrc, frontendDest);

  console.log("\n📦 API (apps/api/src/shared):");
  copyDir(sharedSrc, apiDest);

  console.log("\n✅ Shared files synced successfully!");
  console.log(
    "\n💡 Tip: These files are auto-generated. Edit shared/ instead.\n"
  );
}

try {
  syncShared();
  process.exit(0);
} catch (error) {
  console.error("\n❌ Error syncing shared files:", error.message);
  process.exit(1);
}
